RVMI/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

import spirit.urls

# Override admin login for security purposes
from django.contrib.auth.decorators import login_required
admin.site.login = login_required(admin.site.login)


urlpatterns = [
    re_path(r'^', include(spirit.urls)),

    # This is the default django admin
    # it's not needed to use Spirit
    re_path(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spirit/admin/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, re_path

from . import views
import spirit.category.admin.urls
import spirit.comment.flag.admin.urls
import spirit.topic.admin.urls
import spirit.user.admin.urls


app_name = 'admin'
urlpatterns = [
    re_path(r'^$', views.dashboard, name='index'),
    re_path(r'^dashboard/$', views.dashboard, name='dashboard'),
    re_path(r'^config/$', views.config_basic, name='config-basic'),

    re_path(r'^category/', include(spirit.category.admin.urls)),
    re_path(r'^comment/flag/', include(spirit.comment.flag.admin.urls)),
    re_path(r'^topic/', include(spirit.topic.admin.urls)),
    re_path(r'^user/', include(spirit.user.admin.urls)),
]

spirit/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, re_path

import spirit.topic.views
import spirit.admin.urls
import spirit.user.urls
import spirit.search.urls
import spirit.category.urls
import spirit.topic.urls
import spirit.comment.urls


app_name = 'spirit'
urlpatterns = [
    re_path(r'^$', spirit.topic.views.index_active, name='index'),
    re_path(r'^st/admin/', include(spirit.admin.urls)),
    re_path(r'^user/', include(spirit.user.urls)),
    re_path(r'^search/', include(spirit.search.urls)),
    re_path(r'^category/', include(spirit.category.urls)),
    re_path(r'^topic/', include(spirit.topic.urls)),
    re_path(r'^comment/', include(spirit.comment.urls)),
]

spirit/user/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import re_path, include

from .auth import urls as auth_urls
from . import views


app_name = 'user'
urlpatterns = [
    re_path(r'^$', views.update, name='update'),
    re_path(r'^password-change/$', views.password_change, name='password-change'),
    re_path(r'^email-change/$', views.email_change, name='email-change'),
    re_path(r'^email-change/(?P<token>[0-9A-Za-z_\-\.]+)/$',
        views.email_change_confirm,
        name='email-change-confirm'),
    re_path(r'^unsubscribe/(?P<pk>[0-9]+)/(?P<token>[0-9A-Za-z_\-\.]+)/$',
        views.unsubscribe, name='unsubscribe'),

    re_path(r'^(?P<pk>[0-9]+)/$', views.comments, kwargs={'slug': ""}, name='detail'),
    re_path(r'^(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.comments, name='detail'),

    re_path(r'^topics/(?P<pk>[0-9]+)/$', views.topics, kwargs={'slug': ""}, name='topics'),
    re_path(r'^topics/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.topics, name='topics'),

    re_path(r'^likes/(?P<pk>[0-9]+)/$', views.likes, kwargs={'slug': ""}, name='likes'),
    re_path(r'^likes/(?P<pk>[0-9]+)/(?P<slug>[\w-]+)/$', views.likes, name='likes'),

    re_path(r'^menu/$', views.menu, name='menu'),

    re_path(r'^', include(auth_urls)),
]

spirit/comment/flag/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from ...core.conf import settings

REASON_CHOICES = (
    (0, _("Spam")),
    (1, _("Other")))


class CommentFlag(models.Model):

    moderator = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='st_comment_flags',
        null=True,
        blank=True,
        on_delete=models.CASCADE)
    comment = models.OneToOneField(
        'spirit_comment.Comment',
        on_delete=models.CASCADE)

    date = models.DateTimeField(default=timezone.now)
    is_closed = models.BooleanField(default=False)

    class Meta:
        ordering = ['-date', '-pk']
        verbose_name = _("comment flag")
        verbose_name_plural = _("comments flags")

    # def get_absolute_url(self):
        # pass


class Flag(models.Model):

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='st_flags',
        on_delete=models.CASCADE)
    comment = models.ForeignKey(
        'spirit_comment.Comment',
        on_delete=models.CASCADE)

    date = models.DateTimeField(default=timezone.now)
    reason = models.IntegerField(_("reason"), choices=REASON_CHOICES)
    body = models.TextField(_("body"), blank=True)

    class Meta:
        unique_together = ('user', 'comment')
        ordering = ['-date', '-pk']
        verbose_name = _("flag")
        verbose_name_plural = _("flags")

spirit/admin/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from djconfig.forms import ConfigForm


class BasicConfigForm(ConfigForm):

    site_name = forms.CharField(initial="Spirit", label=_("site name"))
    site_description = forms.CharField(
        initial="", label=_("site description"), max_length=75, required=False)
    template_footer = forms.CharField(
        initial="", label=_("footer snippet"), required=False,
        widget=forms.Textarea(attrs={'rows': 2}),
        help_text=(
            "The footer snippet is no longer supported and "
            "it will be removed in future Spirit versions"))
    comments_per_page = forms.IntegerField(
        initial=20, label=_("comments per page"), min_value=1, max_value=100)
    topics_per_page = forms.IntegerField(
        initial=20, label=_("topics per page"), min_value=1, max_value=100)

spirit/category/admin/forms.py
# -*- coding: utf-8 -*-

import re

from django import forms
from django.db.models import Max
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import smart_str
from django.utils import timezone

from ..models import Category


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = (
            "parent",
            "title",
            "description",
            "is_global",
            "is_closed",
            "is_removed",
            "is_class",
            "color")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        queryset = (
            Category.objects
            .visible()
            .parents()
            .ordered())

        if self.instance.pk:
            queryset = queryset.exclude(pk=self.instance.pk)

        self.fields['parent'] = forms.ModelChoiceField(
            queryset=queryset, required=False)
        self.fields['parent'].label_from_instance = (
            lambda obj: smart_str(obj.title))

    def clean_parent(self):
        parent = self.cleaned_data["parent"]

        if self.instance.pk:
            has_children = self.instance.category_set.all().exists()

            if parent and has_children:
                raise forms.ValidationError(
                    _("The category you are updating "
                      "can not have a parent since it has childrens"))

        return parent

    def clean_color(self):
        color = self.cleaned_data["color"]

        if color and not re.match(r'^#([A-Fa-f0-9]{3}){1,2}$', color):
            raise forms.ValidationError(
                _("The input is not a valid hex color."))

        return color

    def get_max_sort(self):
        return (
            Category.objects
            .aggregate(max_sort=Max('sort'))['max_sort'] or 0)

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.sort = self.get_max_sort() + 1
        self.instance.reindex_at = timezone.now()
        return super().save(commit)

spirit/comment/bookmark/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import CommentBookmark


class BookmarkForm(forms.ModelForm):

    class Meta:
        model = CommentBookmark
        fields = ['comment_number']

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super(BookmarkForm, self).__init__(*args, **kwargs)
        self.user = user
        self.topic = topic

    def save(self, commit=True):
        # Bookmark is created/updated on topic view.
        CommentBookmark.increase_to(
            user=self.user,
            topic=self.topic,
            comment_number=self.cleaned_data['comment_number'])

spirit/comment/flag/admin/forms.py
# -*- coding: utf-8 -*-

from django import forms

from ..models import CommentFlag


class CommentFlagForm(forms.ModelForm):

    class Meta:
        model = CommentFlag
        fields = ("is_closed", )

    def __init__(self, user=None, *args, **kwargs):
        super(CommentFlagForm, self).__init__(*args, **kwargs)
        self.user = user

    def save(self, commit=True):
        self.instance.moderator = self.user
        return super(CommentFlagForm, self).save(commit)

spirit/comment/flag/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _
from django.db import IntegrityError, transaction
from django.utils import timezone

from .models import Flag, CommentFlag


class FlagForm(forms.ModelForm):

    class Meta:
        model = Flag
        fields = ['reason', 'body']

    def __init__(self, user=None, comment=None, *args, **kwargs):
        super(FlagForm, self).__init__(*args, **kwargs)
        self.user = user
        self.comment = comment

    def clean(self):
        cleaned_data = super(FlagForm, self).clean()

        flag = Flag.objects.filter(user=self.user,
                                   comment=self.comment)

        if flag.exists():
            # Do this since some of the unique_together fields are excluded.
            raise forms.ValidationError(_("This flag already exists"))

        return cleaned_data

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.comment = self.comment

            try:
                with transaction.atomic():
                    CommentFlag.objects.update_or_create(
                        comment=self.comment,
                        defaults={'date': timezone.now(), })
            except IntegrityError:
                pass

        return super(FlagForm, self).save(commit)

spirit/comment/forms.py
# -*- coding: utf-8 -*-

import os
import logging

from django import forms
from django.utils.translation import gettext_lazy as _
from django.utils.encoding import smart_bytes
from django.core.files.uploadedfile import TemporaryUploadedFile

from spirit.core.conf import settings
from spirit.core import utils
from spirit.core.storage import spirit_storage
from spirit.core.utils.markdown import Markdown
from spirit.topic.models import Topic
from .poll.models import CommentPoll, CommentPollChoice
from .models import Comment

logger = logging.getLogger(__name__)

# Mostly for Windows users who don't need file upload
try:
    import magic
except ImportError as err:
    # There used to be a logger.exception here but
    # the traceback made things confusing when an unhandled was raised
    if settings.ST_UPLOAD_FILE_ENABLED:
        logger.info(
            'File upload requires running: '
            '`pip install django-spirit[files]`')
        raise err
    magic = None


def save_user_file(user, file, subdir, hashed=False):
    """
    Save user media file into sub-dir. \
    The `hashed`` param prevents file duplication
    """
    file_path = utils.generate_filename(file, hashed=hashed)
    name = os.path.join('spirit', subdir, str(user.pk), file_path)
    name = spirit_storage.save(name, file)
    file.name = os.path.basename(name)
    file.url = spirit_storage.url(name)
    return file


class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label=_('Comment'),
        max_length=settings.ST_COMMENT_MAX_LEN,
        widget=forms.Textarea)
    comment_hash = forms.CharField(
        max_length=32,
        widget=forms.HiddenInput,
        required=False)

    class Meta:
        model = Comment
        fields = ['comment']

    def __init__(self, user=None, topic=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user
        self.topic = topic
        self.mentions = None  # {username: User, }
        self.polls = None  # {polls: [], choices: []}
        # Do not autofocus (when there's initial/instance),
        # we don't know where the cursor should be,
        # and that'd need JS anyway
        self.fields['comment'].widget.attrs['placeholder'] = _("Write comment...")

    def get_comment_hash(self):
        assert self.topic

        # This gets saved into
        # User.last_post_hash,
        # it does not matter whether
        # is a safe string or not
        comment_hash = self.cleaned_data.get('comment_hash', None)

        if comment_hash:
            return comment_hash

        return utils.get_hash((
            smart_bytes(self.cleaned_data['comment']),
            smart_bytes('thread-{}'.format(self.topic.pk))))

    def _get_comment_html(self):
        # user = self.user or self.instance.user
        markdown = Markdown()
        comment_html = markdown.render(self.cleaned_data['comment'])
        self.mentions = markdown.get_mentions()
        self.polls = markdown.get_polls()
        return comment_html

    def _save_polls(self):
        assert self.instance.pk
        assert self.polls is not None

        polls = self.polls['polls']
        choices = self.polls['choices']

        CommentPoll.update_or_create_many(comment=self.instance, polls_raw=polls)
        CommentPollChoice.update_or_create_many(comment=self.instance, choices_raw=choices)

    def save(self, commit=True):
        if not self.instance.pk:
            self.instance.user = self.user
            self.instance.topic = self.topic

        self.instance.comment_html = self._get_comment_html()
        comment = super(CommentForm, self).save(commit)

        if commit:
            self._save_polls()

        return comment


class CommentMoveForm(forms.Form):

    topic = forms.ModelChoiceField(queryset=Topic.objects.all(), widget=forms.TextInput)

    def __init__(self, topic, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['comments'] = forms.ModelMultipleChoiceField(
            queryset=Comment.objects.filter(topic=topic),
            widget=forms.CheckboxSelectMultiple)

    def save(self):
        comments = self.cleaned_data['comments']
        comments_list = list(comments)
        topic = self.cleaned_data['topic']
        comments.update(topic=topic)

        # Update topic in comment instance
        for c in comments_list:
            c.topic = topic

        return comments_list


class CommentImageForm(forms.Form):

    image = forms.ImageField(max_length=255)

    def __init__(self, user=None, *args, **kwargs):
        super(CommentImageForm, self).__init__(*args, **kwargs)
        self.user = user

    def clean_image(self):
        file = self.cleaned_data['image']
        ext = os.path.splitext(file.name)[1].lstrip('.').lower()

        if (ext not in settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT or
                file.image.format.lower() not in settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT):
            raise forms.ValidationError(
                _("Unsupported file format. Supported formats are %s.") %
                  ", ".join(settings.ST_ALLOWED_UPLOAD_IMAGE_FORMAT))

        return file

    def save(self):
        return save_user_file(
            user=self.user,
            file=self.cleaned_data['image'],
            subdir='images',
            hashed=settings.ST_PREVENT_SOME_FILE_DUPLICATION)


class CommentFileForm(forms.Form):

    file = forms.FileField(max_length=255)

    def __init__(self, user=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean_file(self):
        file = self.cleaned_data['file']

        if not magic:
           raise forms.ValidationError(_("The file could not be validated"))

        # Won't ever raise. Has at most one '.' so lstrip is fine here
        ext = os.path.splitext(file.name)[1].lstrip('.').lower()
        if ext not in settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE:
            raise forms.ValidationError(
                _("Unsupported file extension %(extension)s. "
                  "Supported extensions are %(supported)s.") % {
                    'extension': ext,
                    'supported': ", ".join(
                        sorted(settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.keys()))})

        try:
            if isinstance(file, TemporaryUploadedFile):
                file_mime = magic.from_file(file.temporary_file_path(), mime=True)
            else:  # In-memory file
                file_mime = magic.from_buffer(file.read(), mime=True)
        except magic.MagicException as e:
            logger.exception(e)
            raise forms.ValidationError(_("The file could not be validated"))

        mime = settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.get(ext, None)
        if mime != file_mime:
            raise forms.ValidationError(
                _("Unsupported file mime type %(mime)s. "
                  "Supported types are %(supported)s.") % {
                    'mime': file_mime,
                    'supported': ", ".join(
                        sorted(settings.ST_ALLOWED_UPLOAD_FILE_MEDIA_TYPE.values()))})

        return file

    def save(self):
        return save_user_file(
            user=self.user,
            file=self.cleaned_data['file'],
            subdir='files',
            hashed=settings.ST_PREVENT_SOME_FILE_DUPLICATION)

spirit/core/templates/spirit/_base.html
{% load spirit_tags i18n %}
{% load static %}
{% load_settings 'ST_EXTENDED_FONT' %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>{% block title %}{% endblock %} - {{ config.site_name }}</title>
  <meta name="description" content="{{ config.site_description }}">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="{% static "spirit/stylesheets/styles.all.min.css" %}">

  <script src="{% static "spirit/scripts/all.min.js" %}"></script>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      stModules.tab(document.querySelectorAll('.js-tab'));
      stModules.postify(document.querySelectorAll('.js-post'), {
        csrfToken: "{{ csrf_token }}"
      });
      stModules.messages(document.querySelectorAll('.js-messages'));
      {% if user.is_authenticated %}
        stModules.notification(document.querySelectorAll('.js-tab-notification'), {
          notificationUrl: "{% url "spirit:topic:notification:index-ajax" %}",
          notificationListUrl: "{% url "spirit:topic:notification:index-unread" %}",
          mentionTxt: "{% trans "{user} has mention you on {topic}" %}",
          commentTxt: "{% trans "{user} has commented on {topic}" %}",
          showAll: "{% trans "Show all" %}",
          empty: "{% trans "No new notifications, yet" %}",
          unread: "{% trans "unread" %}"
        });
      {% endif %}
      stModules.clickableArea({
        areaClass: '.js-clickable-area',
        targetColor: 'var(--st-text-link-hover)'
      });

    });
  </script>

  {% if st_settings.ST_EXTENDED_FONT %}
    <style>
      @font-face {
        font-family: 'Ubuntu';
        font-style: normal;
        font-weight: 300;
        src: url("{% static "spirit/stylesheets/vendors/fonts/Ubuntu-all-300.woff2" %}") format('woff2'),
        url("{% static "spirit/stylesheets/vendors/fonts/Ubuntu-all-300.woff" %}") format('woff');
      }
    </style>
  {% endif %}

  {% block head-extra %}{% endblock %}
  {% block custom_head_extra %}{% endblock %}
</head>

<body>
<div class="spirit_wrapper">
  <div class="spirit_custom_header">
    {% block custom_before_spirit_body %}{% endblock %}
  </div>
  <div class="spirit">
    <div class="layout">
      {% include 'spirit/_header.html' %}
      {% block content %}{% endblock %}
      {% include 'spirit/_footer.html' %}
    </div>
  </div>
  <div class="spirit_custom_footer">
    {% block custom_after_spirit_body %}{% endblock %}
  </div>
</div>
</body>

</html>

spirit/core/templates/spirit/_footer.html
{% load spirit_tags %}
{% load_settings 'ST_MATH_JAX' %}

{% spaceless %}
<footer class="layout__footer">
  <a class="footer__logo" href="http://www.cs.ecnu.edu.cn/">ECNU-CS</a>
</footer>
{% endspaceless %}

{% if st_settings.ST_MATH_JAX %}
  <script type="text/x-mathjax-config">
    (function () {
      var elms = document.querySelectorAll(".math");
      MathJax.Hub.Config({
        elements: elms,
        skipStartupTypeset: elms.length === 0
      });
    })();
  </script>
  <script type="text/javascript" async
    src="https://cdn.bootcdn.net/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML">
  </script>
{% endif %}

spirit/core/templates/spirit/_form.html
{% if next %}<input type="hidden" name="next" value="{{ next }}" />{% endif %}

{{ form.non_field_errors }}

{% for field in form.hidden_fields %}
  {{ field.errors }}
  {{ field }}
{% endfor %}

{% for field in form.visible_fields %}
  <div class="field">
    {{ field.label_tag }}
    {{ field.errors }}
    {{ field }}
    {{ field.help_text }}
  </div>
{% endfor %}

spirit/core/templates/spirit/_formset.html
{{ formset.management_form }}
{{ formset.non_form_errors }}

{% for f in formset %}
  {% include "spirit/_form.html" with form=f %}
{% endfor %}

spirit/core/templates/spirit/_header.html
{% load spirit_tags i18n %}
{% load_settings 'LOGIN_URL' %}

<header class="layout__header js-tabs-container">
  <div class="header__logo_wrapper">
    {% block custom_header_logo %}
      <a class="header__logo" href="{% url "spirit:index" %}"
      >{{ config.site_name }}</a>
    {% endblock %}
  </div>
  {% if user.is_authenticated %}
    {% has_topic_notifications user as has_notifications %}

    {% spaceless %}
      <ul class="header__tabs">
        <li><a
          class="header__tabs__item js-tab"
          href="{% url "spirit:search:search" %}"
          data-related=".js-search-content"
          ><i class="fa fa-search"></i></a></li>
        <li><a
          class="header__tabs__item js-tab-notification{% if has_notifications %} is-highlighted{% endif %}"
          href="{% url "spirit:topic:notification:index" %}"
          data-related=".js-notifications-content"
          data-content=".js-notifications-content-list"
          ><i class="fa fa-bell"></i></a></li>
        <li><a
          class="header__tabs__item js-tab"
          href="{% url "spirit:user:menu" %}"
          data-related=".js-user-content"
          >{{ user.st.nickname }} <i class="fa fa-chevron-down"></i></a></li>
      </ul>
    {% endspaceless %}

    <div class="header__tabs_content">
      <div class="header__tabs_content__tab js-tab-content js-user-content" style="display: none;">
        <nav class="header__tab__nav">
          {% spaceless %}
          <ul class="menu_list">
            <li><a
              class="menu_list__link"
              href="{% url "spirit:user:detail" pk=user.pk slug=user.st.slug %}"
              >{% trans "Profile" %}</a></li>
            <li><a
              class="menu_list__link"
              href="{% url "spirit:topic:index-active" %}"
              >{% trans "Topics" %}</a></li>
            <li><a
              class="menu_list__link"
              href="{% url "spirit:topic:unread:index" %}"
              >{% trans "Unread topics" %}</a></li>
            <li><a
              class="menu_list__link"
              href="{% url "spirit:topic:private:index" %}"
              >{% trans "Private topics" %}</a></li>
            {% if user.st.is_administrator %}
              <li><a
                class="menu_list__link"
                href="{% url "spirit:admin:index" %}"
                >{% trans "Admin" %}</a></li>
            {% endif %}
            <li><a
              class="menu_list__link js-post"
              href="{% url "spirit:user:auth:logout" %}?next={% firstof request.get_full_path|urlencode '/' %}"
              >{% trans "Log out" %}</a></li>
          </ul>
          {% endspaceless %}
        </nav>
      </div>
      <div class="header__tabs_content__tab js-tab-content js-notifications-content" style="display: none;">
        <div class="header__tab__bell js-notifications-content-list">
        </div>
      </div>
      <div class="header__tabs_content__tab js-tab-content js-search-content" style="display: none;">
        <div class="header__tab__search">
          {% render_search_form %}
        </div>
      </div>
    </div>
  {% else %}
    <a class="header__login"
      href="{% url st_settings.LOGIN_URL %}?next={% firstof request.get_full_path|urlencode '/' %}"
    >{% trans "Log in" %}</a>
  {% endif %}

  {% render_messages messages %}
</header>